### ISSUE TITLE
Scaling for HiDPI displays

### ISSUE THREAD

**Issue by sidosoft** [slavfox/Cozette#28] opened 2020-08-30 23:34 UTC
Hi! While Cozette looks beautiful, it is way to small to be used on HiDPI displays. Would it be possible to scale every glyph by a factor of 2 or more? Or at least could you please advise the best way one can scale an .otb font, pixel-perfectly, so each pixel becomes a 2x2 block? Thank you.

**Comment by sidosoft** [comment] 2020-08-31 09:45
UPDATE: I managed to scale Cozette using this tool for scaling BDF fonts: https://github.com/philj56/bdfscale 
Also, with a minor modification of the above script, I scaled the font so that each pixel becomes 2x3 or 3x4 block. I report that Cozette looks beautiful scaled by 3x4! (See issue #3 which requests a taller variant.)

**Comment by slavfox** [comment] 2020-08-31 10:18
I'm probably not going to provide builds with the scaling applied, but I'll add instructions on how to do that to the README - glad you figured it out and that it works for you!

**Comment by eggjoystick** [comment] 2020-08-31 15:00
> UPDATE: I managed to scale Cozette using this tool for scaling BDF fonts: https://github.com/philj56/bdfscale
> Also, with a minor modification of the above script, I scaled the font so that each pixel becomes 2x3 or 3x4 block. I report that Cozette looks beautiful scaled by 3x4! (See issue #3 which requests a taller variant.)

Can you provide instructions on how to do this please?

**Comment by TheAvidDev** [comment] 2020-08-31 15:20
> Can you provide instructions on how to do this please?

Not OP, but run the python script they linked.

**Comment by eggjoystick** [comment] 2020-08-31 15:27
> > Can you provide instructions on how to do this please?
> 
> Not OP, but run the python script they linked.

Thanks; I was running the script but not correctly outputting a new BDF file. Eventually, I was able to figure out that I needed to add `> cozette-scaled.bdf` to generate the new BDF file.

**Comment by sidosoft** [comment] 2020-08-31 19:47
> Thanks; I was running the script but not correctly outputting a new BDF file. Eventually, I was able to figure out that I needed to add `> cozette-scaled.bdf` to generate the new BDF file.

After scaling, I additionally had to load the scaled .BDF font in FontForge, select all "glyphs worth outputting", and then in Metrics --> Set Width specify the width that is 4/3 times what was there before; then export as .OTB. Without this step, the characters were spaced strangely (on GNU/Linux).  I suspect that this extra step is necessary due to bdfscale not correctly scaling one or more of the font metrics.

**Comment by slavfox** [comment] 2020-09-03 22:00
With that last note, it sounds like something I could provide a build command for to make it simpler. Should happen in the next release.

**Comment by robert5800** [comment] 2021-03-28 11:26
Hi, I am experiencing the same issue with Cozette appearing too small. When I try scaling it using bdfscale with a factor of 2 and then converting it to .otb using FontForge, the font then appears too big. I have been struggling with this for weeks now and I can't figure it out on my own since I don't have a lot of experience working with fonts. Could someone please suggest an alternative method to scale Cozette (of bitmap fonts in general) or send an already scaled version? Any help would be greatly appreciated!

**Comment by tjbarber** [comment] 2022-02-16 17:44
This is still an issue. I love this font and want to use it everywhere, but we need to have support for HiDPI displays. :disappointed:

**Comment by slavfox** [comment] 2023-06-10 07:39
I dropped the ball on this - it's almost three years later, and I forgot about this issue entirely. I'll take a look at shipping scaled-up versions this week.

**Comment by slavfox** [comment] 2023-06-11 03:08
I'm years late, but [v.1.19.2-hidpi](https://github.com/slavfox/Cozette/releases/tag/v.1.19.2-hidpi) is now live; it contains a 2x upscaled version of the bitmap font.

**Comment by nyonson** [comment] 2023-06-12 01:56
Hey @slavfox, I gave the hidpi version a shot and things look a little off on arch using the foot terminal. Is there some step necessary to make these look better?

![swappy-20230611_185557](https://github.com/slavfox/Cozette/assets/1999717/0371879a-b2fb-4022-b5a6-407a96278fe3)

**Comment by slavfox** [comment] 2023-06-12 05:34
What pixel size is this at? Bitmap fonts are intended to render correctly at one and one size only, and the target for `cozette_hidpi` is 26pts.

**Comment by nyonson** [comment] 2023-06-12 12:15
That is with size 26. I tried a few other sizes as well and they all have the same look. Maybe something up with my `foot` terminal settings?

**Comment by slavfox** [comment] 2023-06-12 13:16
Huh, yeah; I can reproduce this in Alacritty. I'll look at it further. Reopening this issue for now.

**Comment by slavfox** [comment] 2023-06-12 13:53
This should be fixed in v1.19.2-hidpi2.
![image](https://github.com/slavfox/Cozette/assets/35173529/f6496b51-1663-4492-9ba6-4607dd6390bd)

**Closed by slavfox** 2023-06-12 13:53 UTC
Labels: build/deployment, documentation
