### ISSUE TITLE
Feature request: Other pixel sizes

### ISSUE THREAD

**Issue by girishji** [slavfox/Cozette#96] opened 2023-06-10 03:34 UTC
Really like this font. But my eyes get tired looking at small size letters. Font sizes like 12x24 would be appreciated.

**Comment by slavfox** [comment] 2023-06-10 07:02
Duplicate of #28, discussion will continue there; thanks for reminding me, I plan to take a look at it when I next have a chance to.

**Closed by slavfox** 2023-06-10 07:02 UTC
